package com.example.intelligentobservabilityservice.service;

import com.example.intelligentobservabilityservice.domain.Alert;
import java.util.List;

public interface AnomalyDetectionService {
    /**
     * Runs all registered detection strategies against recent metrics
     * and returns a list of generated alerts.
     * @param timeWindowInMinutes The time window (in minutes from now) to fetch metrics for.
     * @return A list of alerts generated by the strategies.
     */
    List<Alert> runDetectionStrategies(int timeWindowInMinutes);
}
